<script type="text/javascript" src="/js/ui.spinner.min.js"></script>
<style type="text/css"> @IMPORT url("/css/jquery/ui.spinner.css");</style>

<h1><?= $this->pageTitle; ?></h1>
<?php if (isset($this->message)):?>


<?php $this->hasError = false; ?>

<section class="<?=(isset($this->hasError) ? 'flashMessageValid':'flashMessageError')?>">
	<?= $this->message; ?>
</section>
<?php endif;?>

<a href="<?= $this->link('campaign', 'list', 'admin'); ?>">&lt; Retour</a>
<br>
<br>
Envoyer un mail pour la campagne <strong><?= $this->campaign; ?></strong>
<?= $this->form; ?>
