<h1><?= $this->pageTitle; ?></h1>
<div style="min-height: 200px">
	<div style="width: 990px; height: 150px; padding: 20px 0;">
		<center><h3>Classement campagnes</h3></center>
		<?php foreach($this->campaigns as $campaign){ ?>
		<div class="monthBlock">
			<div class="title"><?echo $campaign[0] ?></div>
			<div class="tops">
				<ol>
					<?php foreach($campaign[1] as $row){ ?>
					<li><?php echo $row["name"] ?> - <?php echo ceil($row["turnover"]) ?> €</li>
					<?php } ?>
				</ol>
			</div>
		</div>
		<?php } ?>
		<br class="clearfloat" />
	</div>
	<div style="width: 990px; height: 150px; padding: 20px 0;margin-top: 30px;">
		<center><h3>Classement Editeurs</h3></center>
		<?php foreach($this->publishers as $publisher){ ?>
		<div class="monthBlock">
			<div class="title"><?echo $publisher[0] ?></div>
			<div class="tops">
				<ol>
					<?php foreach($publisher[1] as $key => $value){ ?>
					<li><?php echo $key ?> - <?php echo ceil($value) ?> €</li>
					<?php } ?>
				</ol>
			</div>
		</div>
		<?php } ?>
	</div>
	<br class="clearfloat" />
</div>
