<?php
    $url = $this->link(null, null, 'admin') . (isset($this->cid)?"?cid={$this->cid}":'');
?>
<section style="background-color: #f3f3f3; padding: 10px; margin-bottom: 15px; position: relative;" id="period">
    <form  action="<?=$url?>">
        <span>Période d'analyse : du 
            <?= $this->datePicker('prev_period', $this->startDate, array('dateFormat' => 'dd/mm/yy')); ?> au <?= $this->datePicker('next_period', $this->endDate, array('dateFormat' => 'dd/mm/yy')); ?>
        </span>
        <input type="submit" id="filter_date" name="filter_date" value="OK" onclick="filter"/>
        <a href="<?=$url?>">Reset</a>
        <?php if(isset($this->cid)):?>
            <input type="hidden" name="cid" value="<?=$this->cid?>"/>
        <?php endif;?>
    </form>
</section>