<style>
<!--
form label {
	display: inline-block;
	width: 145px;
	padding-right: 5px;
	text-align: right;
}
input[type=text], input[type=password] {
	border: 1px solid #ccc;
	width: 184px;
}
form p {
	margin: 5px 0;
}
-->
</style>
<h1>Veuillez vous identifier :</h1>
<form method="post" action="<?php echo $this->link('login', 'login', 'admin'); ?>">&nbsp;
<span class="error"><?php echo $this->errorMessage('loginForm'); ?></span>
<p>
<label for='login'>Identifiant :</label>
<input type='text' name='login' id="login">
</p>
<p>
<label for='password' class="loginlabel">Mot de passe :</label> 
<input type='password' name='password' id="password">
</p>
<p>
<input type='submit' name='submit' value="Connexion" style="margin-left: 156px;" />
</p>
</form>
