<center>
<table cellpadding="0" cellspacing="2" border="0" style="border:2px solid #cccccc; font-family:Verdana, Geneva, sans-serif; font-size:12px; line-height:18px;">
	<tr>
		<td><img src="http://tracking.collecting.fr/images/bandeau.jpg" height="120" width="600" border="0" alt="" /></td>
    </tr>
    <tr>
    	<td align="center">
        	<br />Bonjour <?= $this->firstname; ?>,
            <br /><br /><b>Le nombre de leads de votre campagne '<?= $this->campaign; ?>'</b>
            <br />en co-registration vient d'atteindre les
            <br /><b>90% de son volume total.</b>
            <br /><br />
            Merci de prendre les dispositions nécessaires.
            <br /><br />
            <i>L'interface de co-registration. </i>
            <br /><br />
        </td>
    </tr>
    <tr>
    	<td bgcolor="#e91b86" align="center" height="40"><a href="http://www.baseandco.com/" style="color:#ffffff; text-decoration:underline">www.baseandco.com</a></td>
    </tr>
</table>
</center>
